"""
Model Performance Dashboard.

This page evaluates the classification models used by the
Enterprise Predictive Analytics Engine.

Responsibilities
----------------
1. Load model comparison results.
2. Validate the available evaluation metrics.
3. Identify the best-performing model.
4. Present model-level KPI summaries.
5. Compare Accuracy, Precision, Recall, and F1 Score.
6. Provide a detailed model comparison table.

Architecture
------------
Data loading:
    dashboards.data.loader

Visualization:
    dashboards.components.charts

Reusable UI:
    dashboards.components.kpi_cards
    dashboards.components.section_headers

The page does not retrain models or calculate model metrics
from raw predictions. It uses the existing model comparison
results generated by the project.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st


# ============================================================================
# DATA LAYER
# ============================================================================

from dashboards.data.loader import (
    load_model_comparison,
)


# ============================================================================
# REUSABLE UI COMPONENTS
# ============================================================================

from dashboards.components.charts import (
    bar_chart,
)

from dashboards.components.kpi_cards import (
    kpi_card,
)

from dashboards.components.section_headers import (
    page_header,
    section_header,
)


# ============================================================================
# PAGE HEADER
# ============================================================================

page_header(
    title="Model Performance",
    description=(
        "Compare classification models across accuracy, precision, "
        "recall, and F1 score."
    ),
)


# ============================================================================
# LOAD MODEL COMPARISON DATA
# ============================================================================

try:

    model_df = load_model_comparison()

except FileNotFoundError as exc:

    st.error(
        "Model comparison results could not be found."
    )

    st.caption(str(exc))

    st.stop()

except Exception as exc:

    st.error(
        "An unexpected error occurred while loading model "
        "comparison results."
    )

    st.caption(str(exc))

    st.stop()


# ============================================================================
# DATA VALIDATION
# ============================================================================

if model_df is None or model_df.empty:

    st.warning(
        "Model comparison results are currently unavailable."
    )

    st.stop()


required_columns = {
    "Model",
    "Accuracy",
    "Precision",
    "Recall",
    "F1 Score",
}


missing_columns = (
    required_columns
    - set(model_df.columns)
)


if missing_columns:

    st.error(
        "Model comparison data is missing required columns: "
        + ", ".join(sorted(missing_columns))
    )

    st.stop()


# ============================================================================
# PREPARE MODEL DATA
# ============================================================================

model_df = model_df.copy()


metric_columns = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1 Score",
]


# Convert metric columns safely to numeric values.

for column in metric_columns:

    model_df[column] = pd.to_numeric(
        model_df[column],
        errors="coerce",
    )


# Remove rows where the model name is missing.

model_df = model_df.dropna(
    subset=["Model"]
)


# Remove rows that contain no usable evaluation metrics.

model_df = model_df.dropna(
    subset=metric_columns,
    how="all",
)


if model_df.empty:

    st.warning(
        "No valid model evaluation records are available."
    )

    st.stop()


# ============================================================================
# MODEL RANKING
# ============================================================================

# F1 Score is used as the primary ranking metric because it balances
# precision and recall. This is more informative than selecting a model
# using accuracy alone when classification performance is uneven.

model_df["Performance Score"] = (
    model_df["F1 Score"]
)


model_df = (
    model_df
    .sort_values(
        "Performance Score",
        ascending=False,
    )
    .reset_index(drop=True)
)


# ============================================================================
# BEST MODEL
# ============================================================================

best_model = (
    model_df.iloc[0]
)


best_model_name = (
    best_model["Model"]
)


best_accuracy = (
    best_model["Accuracy"]
)


best_precision = (
    best_model["Precision"]
)


best_recall = (
    best_model["Recall"]
)


best_f1 = (
    best_model["F1 Score"]
)


# ============================================================================
# MODEL PERFORMANCE OVERVIEW
# ============================================================================

section_header(
    title="Performance Overview",
    description=(
        "Summary of the strongest classification model across the "
        "available evaluation metrics."
    ),
)


kpi_columns = st.columns(
    4,
    gap="large",
)


# ----------------------------------------------------------------------------
# BEST MODEL
# ----------------------------------------------------------------------------

with kpi_columns[0]:

    kpi_card(
        label="Best Model",
        value=str(best_model_name),
        delta="Highest F1 Score",
        delta_type="positive",
    )


# ----------------------------------------------------------------------------
# ACCURACY
# ----------------------------------------------------------------------------

with kpi_columns[1]:

    kpi_card(
        label="Accuracy",
        value=f"{best_accuracy:.1%}",
        delta=str(best_model_name),
        delta_type="positive",
    )


# ----------------------------------------------------------------------------
# PRECISION
# ----------------------------------------------------------------------------

with kpi_columns[2]:

    kpi_card(
        label="Precision",
        value=f"{best_precision:.1%}",
        delta=str(best_model_name),
        delta_type="neutral",
    )


# ----------------------------------------------------------------------------
# RECALL
# ----------------------------------------------------------------------------

with kpi_columns[3]:

    kpi_card(
        label="Recall",
        value=f"{best_recall:.1%}",
        delta=str(best_model_name),
        delta_type="neutral",
    )


# ============================================================================
# F1 SCORE HIGHLIGHT
# ============================================================================

section_header(
    title="Primary Model Selection Metric",
    description=(
        "F1 Score balances precision and recall and is used here as "
        "the primary metric for ranking the available models."
    ),
)


f1_columns = st.columns(
    2,
    gap="large",
)


with f1_columns[0]:

    kpi_card(
        label="Best F1 Score",
        value=f"{best_f1:.1%}",
        delta=str(best_model_name),
        delta_type="positive",
    )


with f1_columns[1]:

    kpi_card(
        label="Models Evaluated",
        value=f"{len(model_df):,}",
        delta="Classification models",
        delta_type="neutral",
    )


# ============================================================================
# ACCURACY COMPARISON
# ============================================================================

section_header(
    title="Accuracy Comparison",
    description=(
        "Compare overall prediction accuracy across the evaluated models."
    ),
)


accuracy_chart_df = model_df[
    [
        "Model",
        "Accuracy",
    ]
].copy()


bar_chart(
    dataframe=accuracy_chart_df,
    x="Model",
    y="Accuracy",
    title="Model Accuracy",
    x_title="Model",
    y_title="Accuracy",
    height=380,
)


# ============================================================================
# PRECISION COMPARISON
# ============================================================================

section_header(
    title="Precision Comparison",
    description=(
        "Compare the proportion of predicted positive cases that "
        "were correctly identified."
    ),
)


precision_chart_df = model_df[
    [
        "Model",
        "Precision",
    ]
].copy()


bar_chart(
    dataframe=precision_chart_df,
    x="Model",
    y="Precision",
    title="Model Precision",
    x_title="Model",
    y_title="Precision",
    height=380,
)


# ============================================================================
# RECALL COMPARISON
# ============================================================================

section_header(
    title="Recall Comparison",
    description=(
        "Compare the proportion of actual positive cases correctly "
        "identified by each model."
    ),
)


recall_chart_df = model_df[
    [
        "Model",
        "Recall",
    ]
].copy()


bar_chart(
    dataframe=recall_chart_df,
    x="Model",
    y="Recall",
    title="Model Recall",
    x_title="Model",
    y_title="Recall",
    height=380,
)


# ============================================================================
# F1 SCORE COMPARISON
# ============================================================================

section_header(
    title="F1 Score Comparison",
    description=(
        "Compare the balance between precision and recall across "
        "the evaluated models."
    ),
)


f1_chart_df = model_df[
    [
        "Model",
        "F1 Score",
    ]
].copy()


bar_chart(
    dataframe=f1_chart_df,
    x="Model",
    y="F1 Score",
    title="Model F1 Score",
    x_title="Model",
    y_title="F1 Score",
    height=380,
)


# ============================================================================
# MODEL COMPARISON TABLE
# ============================================================================

section_header(
    title="Model Comparison Detail",
    description=(
        "Detailed evaluation metrics for every classification model."
    ),
)


display_df = model_df[
    [
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
    ]
].copy()


# Convert decimal metrics into percentage values for presentation.

for column in metric_columns:

    display_df[column] = (
        display_df[column] * 100
    )


# Rename columns for a cleaner dashboard table.

display_df = display_df.rename(
    columns={
        "Model": "Model",
        "Accuracy": "Accuracy (%)",
        "Precision": "Precision (%)",
        "Recall": "Recall (%)",
        "F1 Score": "F1 Score (%)",
    }
)


# Display the table using native Streamlit rendering.
#
# Native rendering is intentionally used instead of manually constructed
# HTML so that the table remains stable and avoids the raw HTML problem
# encountered earlier in the project.

st.dataframe(
    display_df,
    width="stretch",
    hide_index=True,
    height=180,
    column_config={

        "Model": st.column_config.TextColumn(
            "Model",
            width="large",
        ),

        "Accuracy (%)": st.column_config.NumberColumn(
            "Accuracy (%)",
            format="%.1f%%",
        ),

        "Precision (%)": st.column_config.NumberColumn(
            "Precision (%)",
            format="%.1f%%",
        ),

        "Recall (%)": st.column_config.NumberColumn(
            "Recall (%)",
            format="%.1f%%",
        ),

        "F1 Score (%)": st.column_config.NumberColumn(
            "F1 Score (%)",
            format="%.1f%%",
        ),
    },
)


# ============================================================================
# MODEL SELECTION SUMMARY & FEATURE IMPORTANCE
# ============================================================================

section_header(
    title="Champion Model Selection & Feature Importance",
    description=(
        "The champion classifier is selected based on optimal F1 Score balance, "
        "minimizing false alarms while capturing dissatisfied customer experiences."
    ),
)

st.info(
    f"**Production Champion:** {best_model_name}  \n"
    f"• **F1 Score:** {best_f1:.1%} (Highest balanced precision & recall)  \n"
    f"• **Accuracy:** {best_accuracy:.1%} | **Precision:** {best_precision:.1%} | **Recall:** {best_recall:.1%}  \n"
    f"• **Deployment Strategy:** Proactively flag high-risk orders before review submission to trigger proactive delivery SLAs.",
    icon="🏆",
)

try:
    from dashboards.data.loader import load_classification_model

    artifact = load_classification_model()
    if "feature_importances" in artifact and artifact["feature_importances"]:
        fi_df = pd.DataFrame(artifact["feature_importances"]).head(8)
        fi_df["Feature"] = fi_df["feature"].apply(lambda x: x.replace("_", " ").replace("cat ", "Category: ").title())
        fi_df["Importance (%)"] = fi_df["importance"] * 100

        section_header(
            title="Random Forest Feature Importance",
            description="Relative influence of each operational and economic feature in predicting low review risk.",
        )

        bar_chart(
            dataframe=fi_df,
            x="Feature",
            y="Importance (%)",
            title="Top Feature Importances in Dissatisfaction Classification",
            x_title="Feature",
            y_title="Relative Importance (%)",
            height=380,
        )
except Exception:
    pass