"""
Centralized HTML rendering utilities.

This module provides the single approved mechanism for rendering
custom HTML inside the dashboard.

Why this exists
---------------
The dashboard uses custom HTML for premium UI components such as:

    - KPI cards
    - Insight cards
    - Status badges
    - Branded headers
    - Custom panels

Instead of calling st.markdown(..., unsafe_allow_html=True)
throughout the application, all custom HTML is routed through
this module.

This prevents inconsistent rendering and reduces the chance of
raw HTML being displayed as Markdown code.
"""

import streamlit as st


def render_html(html: str) -> None:
    """
    Render trusted application HTML using Streamlit's HTML renderer.

    Parameters
    ----------
    html:
        HTML string generated by the application's own components.

    Notes
    -----
    Only trusted, application-generated HTML should be passed here.
    Do not pass raw user input directly into this function.
    """

    if not isinstance(html, str):
        raise TypeError(
            "render_html() expects an HTML string."
        )

    if not html.strip():
        return

    # st.html() is specifically designed for rendering HTML/CSS.
    # It avoids Markdown's code-block interpretation of indented HTML.
    st.html(html)